/// Flutter icons HavyakaIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  HavyakaIcons
///      fonts:
///       - asset: fonts/HavyakaIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class HavyakaIcons {
  HavyakaIcons._();

  static const _kFontFam = 'HavyakaIcons';
  static const String? _kFontPkg = null;

  static const IconData upnayan =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ganesha =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData namaste =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData kalasha =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rama =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData swastik =
      IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wedding =
      IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData baby =
      IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
